services:
  web:
    image: nginx
    ports:
      - 85:80
    volumes:
      - '/home/ochir/projects/environment/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - '.:/var/www/html'
  php-fpm:
    build: ../online-shop/docker/php
    volumes:
      - '.:/var/www/html'
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}